---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jgoodhcg

resources:
  - namespace.yaml
  - ingress.yaml
  - service.yaml
  - deployment.yaml

images:
  - name: image-tag-goes-here
    newName: docker.io/jgoodhcg/umeng-dev
    newTag: dev
